# Generated by Django 5.2 on 2025-05-02 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tag_thread_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'verbose_name': 'Like', 'verbose_name_plural': 'Likes'},
        ),
        migrations.AlterModelOptions(
            name='thread',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thread', 'verbose_name_plural': 'Threads'},
        ),
    ]
