# Generated by Django 5.2 on 2025-05-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_comment_options_rename_content_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thread',
            options={},
        ),
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='thread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
