# Generated by Django 5.2 on 2026-05-07 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_comment_options_alter_like_options_and_more'),
        ('forums', '0002_post_is_sage'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threads', to='forums.board'),
        ),
        migrations.AddField(
            model_name='thread',
            name='bump_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
