# Generated by Django 5.2 on 2026-05-07 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_thread_board_thread_bump_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='posts_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
