# Generated by Django 5.2 on 2026-05-07 15:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(choices=[('thread', 'Тред'), ('comment', 'Комментарий'), ('post', 'Пост')], max_length=20, verbose_name='Тип контента')),
                ('content_id', models.PositiveIntegerField(verbose_name='ID контента')),
                ('content_data', models.JSONField(default=dict, verbose_name='Данные контента')),
                ('reason', models.TextField(blank=True, verbose_name='Причина жалобы')),
                ('toxicity_score', models.FloatField(blank=True, null=True, verbose_name='Оценка токсичности')),
                ('status', models.CharField(choices=[('pending', 'В ожидании'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('deleted', 'Удалено')], default='pending', max_length=20, verbose_name='Статус')),
                ('moderated_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата модерации')),
                ('moderator_comment', models.TextField(blank=True, verbose_name='Комментарий модератора')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('moderated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_content', to=settings.AUTH_USER_MODEL, verbose_name='Модератор')),
                ('reported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_content', to=settings.AUTH_USER_MODEL, verbose_name='Пожаловался')),
            ],
            options={
                'verbose_name': 'Очередь модерации',
                'verbose_name_plural': 'Очереди модерации',
                'ordering': ['-created_at'],
            },
        ),
    ]
