# Generated by Django 5.2 on 2026-05-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_sage',
            field=models.BooleanField(default=False, verbose_name='Sage (без бампа)'),
        ),
    ]
